apiVersion: v1
kind: ConfigMap
metadata:
  name: example
  namespace: federatorai
data:
  example.property.1: hello
  example.property.2: world
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3
