apiVersion: v1
kind: Service
metadata:
  labels:
    app: kroos-service
  name: kroos-service
  namespace: kroos-tutorial
spec:
  ports:
  - name: grpc
    port: 50050
  selector:
    app: kroos-service