apiVersion: v1
kind: ConfigMap
metadata:
  name: federatorai-agent-gpu-config
  namespace: {{.NameSpace}}
data:
  transmitter.toml: |-
    [log]
     set-logcallers = false
     output-level = "info" # debug, info, warn, error, fatal, none

    [input_jobs]
        [input_jobs.gpucollection]
        name = "gpu_collection"
        schedule-spec = "@every 3s"
        lib-path = "/lib/inputlib/prometheusgpu.so"
        lib-configuration = "/etc/alameda/federatorai-agent/input/influx_prometheus.toml"

  influx_prometheus.toml: |
    [global]
    interval = 300

    [target]
    datatype = "influx"
    address = "alameda-datahub.{{.NameSpace}}.svc:50050"
    port = ""
    username = "admin"
    password = "adminpass"
    database = "alameda_gpu"

    [datasource]
    [datasource.influx]
    datatype = "influx"
    address = "{{.FederatoraiAgentGPU.Datasource.InfluxDB.Address}}"
    port = ""
    username = "{{.FederatoraiAgentGPU.Datasource.InfluxDB.Username}}"
    password = "{{.FederatoraiAgentGPU.Datasource.InfluxDB.Password}}"
    database = "gpu_counting"

    [[datasource.influx.measurement]]
    name = "gpu_counting_k8s"
    expr = "select * from k8s"
    last_seconds = "300"
    tags = ["NodeName", "Poding", "PodName", "ProjCode", "ProjCreator", "ProjType", "img_type", "namespace", "prj_type", "resource", "type"]
    [datasource.influx.measurement.element.value]
    type = "float"

    [datasource.prometheus]
    datatype = "prometheus"
    address = "{{.FederatoraiAgentGPU.Datasource.Prometheus.Address}}"
    port = ""
    username = "{{.FederatoraiAgentGPU.Datasource.Prometheus.Username}}"
    password = "{{.FederatoraiAgentGPU.Datasource.Prometheus.Password}}"

    [[datasource.prometheus.measurement]]
    name = "nvidia_gpu_duty_cycle"
    expr = "nvidia_gpu_duty_cycle"
    tags = ["host", "instance", "job", "name", "uuid"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "nvidia_gpu_num_devices"
    expr = "nvidia_gpu_num_devices"
    tags = ["host", "instance", "job"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "nvidia_gpu_memory_used_bytes"
    expr = "nvidia_gpu_memory_used_bytes"
    tags = ["host", "instance", "job", "name", "uuid"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "nvidia_gpu_memory_total_bytes"
    expr = "nvidia_gpu_memory_total_bytes"
    tags = ["host", "instance", "job", "name", "uuid"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "nvidia_gpu_temperature_celsius"
    expr = "nvidia_gpu_temperature_celsius"
    tags = ["host", "instance", "job", "name", "uuid"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "nvidia_gpu_power_usage_milliwatts"
    expr = "nvidia_gpu_power_usage_milliwatts"
    tags = ["host", "instance", "job", "name", "uuid"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "overall_gpu_memory_utilizatin"
    expr = "sum(nvidia_gpu_memory_used_bytes) / sum(nvidia_gpu_memory_total_bytes)"
    last_seconds = "1"
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "nodes_of_gpu_memory_utilization"
    expr = "sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host)"
    last_seconds = "1"
    tags = ["host"]
    [datasource.prometheus.measurement.element.value]
    type = "float"

    [[datasource.prometheus.measurement]]
    name = "uuid_of_gpu_memory_utilization"
    expr = "nvidia_gpu_memory_used_bytes / nvidia_gpu_memory_total_bytes"
    last_seconds = "1"
    tags = ["host", "instance", "job", "name", "uuid"]
    [datasource.prometheus.measurement.element.value]
    type = "float"